spring.application.name=matching-service

server.port=8082
user-service.url=http://localhost:8080
cors.allowed-origins=http://localhost:5173,http://localhost:5174

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.redis.host=localhost
spring.redis.port=6379

rabbitmq.queue.name=peerprep-queue
rabbitmq.exchange.name=peerprep-exchange
rabbitmq.routing.key=peerprep-routing-key
logging.level.com.g13cs3219.matching_service.services.ProducerService=WARN